### PR TITLE
Add re-identify method

### PR DESCRIPTION
**Pull request by chexton**
Hi guys, we're keen to add support for re-identify here. You may find it useful. If you would like us to take ownership of this repository, please let us know.

CH

### CODE REVIEW

**Comment by ryanwilsonperkin** [comment]
Hey Chris, thanks for the contribution, I'll discuss with the team whether we'd like to turn over ownership,. You can always notify us of new features through GitHub issues as well and we'd be happy to setup new endpoints.

Before we merge this, can you add an example usage to `README.rst` and `docs/index.rst`?

**Comment by chexton** [comment]
Hey @ryanwilsonperkin – done mate.

Happy for you guys to maintain as you see fit, just wanted to offer :).

**Comment by ryanwilsonperkin** [comment]
Thanks @chexton. We're happy to keep maintaining, and enjoy having some open source contributions. 

There's one more spot to add an example: in `docs/index.rst`. That's where we generate docs from for [ReadTheDocs](http://vero.readthedocs.org/en/latest/).

**Comment by chexton** [comment]
@ryanwilsonperkin right you are – done...I think.

**Pull request merged**
