### PR TITLE
use semver ranges for deps.

### PR DESCRIPTION
**Pull request by graingert**
requests 3 will come out, and it will break backwards compatibility

### CODE REVIEW

**Comment by ryanwilsonperkin** [comment]
Hi @graingert, thanks so much for contributing this PR!

Could you explain a bit more about why you think we should restrict these versions? It's the maintainers' opinion that we aren't opinionated about which version of these libraries we're using, so long as the major version changes don't impact the APIs that we're making use of. Since the dependencies aren't pinned, developers using this library can feel free to pin the subdependencies to whichever version they require.

**Comment by graingert** [comment]
@ryanwilsonperkin if someone has in their requirements.txt:

```sh
echo vero==2.0.1 > ./requirements.txt
```

then starts writing code using vero....

then sometime later requests 3.0 or mock 3.0 are released with breaking changes. (requests has a plan in place for this already)

```
pip install -r requirements.txt
```

trying to run the project with fail!

**Comment by ryanwilsonperkin** [comment]
Any breaking dependencies in `mock` shouldn't be an issue for developers using this library, since it's only installed in dependencies for testing this package.

For `requests` though, you're right that a developer might be surprised by a change in the API, but if they're explicitly using certain features in the response object that is returned, it would be their prerogative to pin a version of requests that works for them.

Consider also that if we pinned `requests`, it would _prevent_ developers of this library from using the latest version, even if they were okay with the new changes.

**Comment by graingert** [comment]
@ryanwilsonperkin it's recommended to use a semver version range in packages

**Comment by ryanwilsonperkin** [comment]
@graingert only when your package depends on elements of the other package that are changed between major versions. As far as I could tell from reading https://github.com/requests/requests/pull/3864 there aren't any changes intended for the `requests.request` function that this package makes use of.

**Comment by graingert** [comment]
@ryanwilsonperkin but you don't know what *could* be added, or what would happen with requests 4.

**Comment by ryanwilsonperkin** [comment]
@graingert that's a great point! This sounds like a difference of opinion over how opinionated the library should be. We're of the opinion that this library should be as permissive as possible, and only place restrictions on it's sub-dependencies if/when they break the API.

We'll continue to monitor those libraries, and to some degree you'd have to trust us to put the appropriate restrictions in place if they introduce breaking changes. But if you're uncomfortable with that, I'd recommend that you place your own restriction on `requests` in your `requirements.txt`.

**Comment by mwarkentin** [comment]
@graingert can I also recommend [pipenv](https://pipenv.readthedocs.io/en/latest/) as well as an option for end users to lock down all sub-dependencies to a known working version if that's a large concern?

**Comment by graingert** [comment]
pipenv provides a feature to automatically upgrade to safe packages based
on the version ranges of the entire dep graph

**Comment by ryanwilsonperkin** [comment]
@graingert thanks again for bringing up this topic, but it remains our opinion that we shouldn't pin specific versions of requests. If we find that a version is released with breaking changes, we will certainly update this library to pin it more strictly, or update to support the new APIs.

In the meantime, I would agree with @mwarkentin on the recommendation to investigate a tool like `pipenv` for strict requirements on your own projects.

Thanks!

**Pull request closed without merging**
